-- ENUM Types
CREATE TYPE product_type_enum AS ENUM ('physical', 'digital', 'reservation', 'subscription', 'other');
CREATE TYPE unit_type_enum AS ENUM ('G', 'KG', 'L', 'ML', 'PCS', 'PAX', 'PERSON', 'ROOM', 'PACK', 'QTY', 'LBS', 'HOUR', 'BOX');
CREATE TYPE option_type_enum AS ENUM ('text', 'number', 'date', 'checkbox', 'select');
CREATE TYPE delivery_method_enum AS ENUM ('pickup', 'delivery', 'dine_in');
CREATE TYPE order_status_enum AS ENUM ('new', 'sent_to_whatsapp', 'processing', 'completed', 'cancelled');
CREATE TYPE event_type_enum AS ENUM ('page_view', 'product_view', 'add_to_cart', 'whatsapp_click', 'order_generated');

-- ENTERPRISES
CREATE TABLE IF NOT EXISTS public.enterprises (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID REFERENCES auth.users(id) NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- STORES
CREATE TABLE IF NOT EXISTS public.stores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  enterprise_id UUID REFERENCES public.enterprises(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  image_url TEXT,
  phone TEXT,
  color TEXT DEFAULT '#25D366',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- CATEGORIES
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- TAGS
CREATE TABLE IF NOT EXISTS public.tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
  name TEXT NOT NULL
);

-- PRODUCTS
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,

  name TEXT NOT NULL,
  type product_type_enum DEFAULT 'physical',
  sku TEXT,
  description TEXT,
  images JSONB,

  price NUMERIC NOT NULL DEFAULT 0,
  original_price NUMERIC,
  show_estimated_price BOOLEAN DEFAULT FALSE,
  track_cost BOOLEAN DEFAULT FALSE,
  cost_price NUMERIC,
  show_net_price BOOLEAN DEFAULT FALSE,

  unit_value NUMERIC,
  unit unit_type_enum DEFAULT 'PCS',

  tax_exempt BOOLEAN DEFAULT FALSE,
  tax_exempt_reason TEXT,

  requires_shipping BOOLEAN DEFAULT TRUE,
  delivery_methods TEXT[],

  is_visible BOOLEAN DEFAULT TRUE,
  is_out_of_stock BOOLEAN DEFAULT FALSE,
  track_inventory BOOLEAN DEFAULT FALSE,
  stock_quantity INTEGER DEFAULT 0,
  daily_capacity INTEGER,
  max_order_quantity INTEGER,
  min_order_quantity INTEGER DEFAULT 1,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- VARIANTS
CREATE TABLE IF NOT EXISTS public.variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  original_price NUMERIC,
  image_url TEXT
);

-- OPTIONS
CREATE TABLE IF NOT EXISTS public.options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type option_type_enum DEFAULT 'text',
  values JSONB,
  is_required BOOLEAN DEFAULT FALSE
);

-- CLIENTS
CREATE TABLE IF NOT EXISTS public.clients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  alt_phone TEXT,
  email TEXT,
  birthday DATE,
  address TEXT,
  notes TEXT,
  referral_code TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- CLIENT TAGS (junction)
CREATE TABLE IF NOT EXISTS public.client_tags (
  client_id UUID REFERENCES public.clients(id) ON DELETE CASCADE,
  tag_id BIGINT REFERENCES public.tags(id) ON DELETE CASCADE,
  PRIMARY KEY (client_id, tag_id)
);

-- PRODUCT TAGS (junction)
CREATE TABLE IF NOT EXISTS public.product_tags (
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  tag_id BIGINT REFERENCES public.tags(id) ON DELETE CASCADE,
  PRIMARY KEY (product_id, tag_id)
);

-- ORDERS
CREATE TABLE IF NOT EXISTS public.orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
  client_id UUID REFERENCES public.clients(id) ON DELETE SET NULL,

  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_email TEXT,
  delivery_address TEXT,

  total_amount NUMERIC NOT NULL,
  delivery_fee NUMERIC DEFAULT 0,
  status order_status_enum DEFAULT 'new',
  whatsapp_message TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ORDER ITEMS
CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  variant_id BIGINT REFERENCES public.variants(id) ON DELETE SET NULL,

  product_name TEXT NOT NULL,
  unit_price NUMERIC NOT NULL,
  quantity INTEGER NOT NULL,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- DELIVERY ZONES
CREATE TABLE IF NOT EXISTS public.delivery_zones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  base_fee NUMERIC NOT NULL DEFAULT 0,
  min_order_for_free NUMERIC
);

-- ANALYTICS LOG
CREATE TABLE IF NOT EXISTS public.analytics_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
  event_type event_type_enum NOT NULL,
  resource_id TEXT,
  ip_address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
