ALTER TABLE public.variants
  ADD COLUMN IF NOT EXISTS track_inventory BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS stock_quantity INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_order_quantity INTEGER,
  ADD COLUMN IF NOT EXISTS is_out_of_stock BOOLEAN DEFAULT FALSE;

ALTER TABLE public.order_items
  ADD COLUMN IF NOT EXISTS options JSONB;
