CREATE TYPE order_status_enum AS ENUM ('new', 'sent_to_whatsapp', 'processing', 'completed', 'cancelled');
CREATE TYPE event_type_enum AS ENUM ('page_view', 'product_view', 'add_to_cart', 'whatsapp_click', 'order_generated');

ALTER TYPE delivery_method_enum ADD VALUE IF NOT EXISTS 'deguster_sur_place';

ALTER TABLE products
  ALTER COLUMN delivery_methods TYPE delivery_method_enum[]
  USING CASE
    WHEN delivery_methods IS NULL THEN NULL
    ELSE ARRAY(SELECT unnest(delivery_methods)::delivery_method_enum)
  END;

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    delivery_address TEXT,
    total_amount NUMERIC NOT NULL DEFAULT 0,
    delivery_fee NUMERIC DEFAULT 0,
    status order_status_enum DEFAULT 'new',
    whatsapp_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    variant_id BIGINT REFERENCES variants(id) ON DELETE SET NULL,
    unit_price NUMERIC NOT NULL,
    quantity INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE delivery_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    base_fee NUMERIC NOT NULL DEFAULT 0,
    min_order_for_free NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE analytics_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
    event_type event_type_enum NOT NULL,
    resource_id BIGINT,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
