-- 1. Création des Types ENUM (Listes de choix fixes)
CREATE TYPE product_type_enum AS ENUM ('physique', 'numerique', 'reservation', 'abonnement', 'autres');
CREATE TYPE unit_type_enum AS ENUM ('G', 'KG', 'L', 'ML', 'PCS', 'PAX', 'PERSON', 'ROOM', 'PACK', 'QTY', 'LBS', 'HOUR', 'BOX');
CREATE TYPE option_type_enum AS ENUM ('text', 'number', 'date', 'checkbox', 'select');
CREATE TYPE delivery_method_enum AS ENUM ('emporter', 'livraison', 'sur_place');

-- 2. Table ENTREPRISE (Liée au user Supabase)
CREATE TABLE enterprises (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID REFERENCES auth.users(id) NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table MAGASIN (Stores)
CREATE TABLE stores (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    enterprise_id UUID REFERENCES enterprises(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    image_url TEXT,
    phone TEXT,
    color TEXT DEFAULT '#25D366',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Table CATEGORIES
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Table TAGS (Etiquettes partagées Produits et Clients)
CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
    name TEXT NOT NULL
);

-- 6. Table PRODUITS (Products)
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    
    name TEXT NOT NULL,
    type product_type_enum DEFAULT 'physique',
    sku TEXT,
    description TEXT,
    images JSONB,
    tags_list JSONB,

    price NUMERIC NOT NULL DEFAULT 0,
    original_price NUMERIC,
    show_estimated_price BOOLEAN DEFAULT FALSE,
    track_cost BOOLEAN DEFAULT FALSE,
    cost_price NUMERIC,
    show_net_price BOOLEAN DEFAULT FALSE,

    unit_value NUMERIC,
    unit unit_type_enum DEFAULT 'PCS',
    
    tax_exempt BOOLEAN DEFAULT FALSE,
    tax_exempt_reason TEXT,
    
    requires_shipping BOOLEAN DEFAULT TRUE,
    delivery_methods TEXT[],
    
    is_visible BOOLEAN DEFAULT TRUE,
    is_out_of_stock BOOLEAN DEFAULT FALSE,
    track_inventory BOOLEAN DEFAULT FALSE,
    stock_quantity INTEGER DEFAULT 0,
    daily_capacity INTEGER,
    max_order_quantity INTEGER,
    min_order_quantity INTEGER DEFAULT 1,
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Table VARIANTES (Variants)
CREATE TABLE variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    original_price NUMERIC,
    image_url TEXT
);

-- 8. Table OPTIONS (Pour la personnalisation client)
CREATE TABLE options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type option_type_enum DEFAULT 'text',
    values JSONB,
    is_required BOOLEAN DEFAULT FALSE
);

-- 9. Table CLIENTS (Isolés par magasin)
CREATE TABLE clients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    alt_phone TEXT,
    email TEXT,
    birthday DATE,
    address TEXT,
    notes TEXT,
    referral_code TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Table Liaison CLIENTS <-> TAGS
CREATE TABLE client_tags (
    client_id UUID REFERENCES clients(id) ON DELETE CASCADE,
    tag_id BIGINT REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (client_id, tag_id)
);

-- 11. Table Liaison PRODUITS <-> TAGS
CREATE TABLE product_tags (
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    tag_id BIGINT REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, tag_id)
);
